Image and input
Megha-Joshi/Component_Library pull request #4
Opened 2022-02-09 07:15 UTC by Megha-Joshi

![Screenshot (46)](https://user-images.githubusercontent.com/94787797/153140009-5193108d-a466-4b09-8f04-0ca5dde05e55.png)
![Screenshot (47)](https://user-images.githubusercontent.com/94787797/153140032-496d7dd0-6598-4079-a26f-ea1b89cfbef5.png)
![Screenshot (48)](https://user-images.githubusercontent.com/94787797/153140043-ad57db1f-3ef0-4661-a4df-cc85230654ee.png)
![Screenshot (49)](https://user-images.githubusercontent.com/94787797/153140280-9a341740-3150-4dbd-9efb-4c953d7f9ca1.png)
![Screenshot (50)](https://user-images.githubusercontent.com/94787797/153140302-5337e5b5-5cee-4e1b-b61b-01156b10f694.png)

This is my image and input component. I still have to add carbon code.

2022-02-09 09:44 UTC, dev-enforced approved these changes
Code and output generated by it be it the Image and input ones looks good to me !! You can merge it once you add the carbon related code

2022-02-09 10:07 UTC, adith-a-danthi requested changes
Looks good! Try to use semantic tags `header`, `aside`, `main`.

2022-02-09 10:07 UTC, adith-a-danthi commented on css/nav.css
> +    height: 12.5rem;
These units could have been in `px` itself

2022-02-09 10:07 UTC, adith-a-danthi commented on Components/Image/image.html
> +    <div class="container">
You can replace `div` with a semantic tag `header`

2022-02-09 10:07 UTC, adith-a-danthi commented on Components/Image/image.html
> +    <div class="main">
You can use `main` tag instead of `div` and `aside` for the sidebar

2022-02-18 10:25 UTC, Jia-A approved these changes
Nice use of variables throughout the code. Good formatting. Ready to merge.

2022-02-18 10:26 UTC, merged